project:
  type: website
  output-dir: docs

website:
  title: "sonsoleslp"
  description: "Personal website of Sonsoles López Pernas"
  site-url: https://sonsoleslp.github.io
  repo-url: https://github.com/sonsoleslp/sonsoleslp.github.io
  google-analytics: "G-251HR7GW52"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@sonsoleslp"
    site: "@sonsoleslp"
    card-style: "summary_large_image"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: publications.qmd
      - href: softwares.qmd
      # - href: blog.qmd
  page-footer:
    left:
      - text: '<a class="btn btn-dark btn-social" style=" border: none;"  href="https://github.com/sonsoleslp" target="_blank" rel="noopener noreferrer"><i class="bi bi-github" role="img"" aria-label="Github"></i></a><a class="btn btn-primary btn-social"  style="background-color: #0B65C2; border: none;"  href="https://www.linkedin.com/in/drew-dimmery/" target="_blank" rel="noopener noreferrer"><i class="bi bi-linkedin" role="img" aria-label="LinkedIn"></i></a><a class="btn btn-primary btn-social"  style="background-color: #3F80EC; border: none;"  href="https://scholar.google.com/citations?user=67eUI4gAAAAJ" target="_blank" rel="noopener noreferrer"><i class="ai ai-google-scholar" role="img"" aria-label="Google Scholar"></i></a><a class="btn btn-info btn-social" style="background-color: #188CD8; border: none;"  href="https://twitter.com/sonsoleslp" target="_blank" rel="noopener noreferrer"><i class="bi bi-twitter" role="img"" aria-label="Twitter"></i></a><a class="btn btn-primary btn-social" style="background-color: #00D0AE; border: none;" href="https://www.researchgate.net/profile/Sonsoles-Lopez-Pernas" target="_blank" rel="noopener noreferrer"><i class="ai ai-researchgate" role="img"" aria-label="Research Gate"></i></a><a class="btn btn-success btn-social" style="background-color: #A6CE39; border: none;" href="https://orcid.org/0000-0002-9621-1392" target="_blank" rel="noopener noreferrer"><i class="ai ai-orcid" role="img"" aria-label="Orcid"></i></a>'
    right: 
      - text: '<span style="text-sm"><a target="_blank" href="https://github.com/sonsoleslp/sonsolelp.github.io">Source code</a>. Based on <a target="_blank" href="https://github.com/ddimmery/quarto-website">ddimmery</a></span>'
format:
  html:
    theme: 
      - litera
      - custom.scss
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
resources:
  - CNAME