project:
  type: website
  output-dir: docs

website:
  title: "sonsoleslp"
  description: "Personal website of Sonsoles López Pernas"
  site-url: https://sonsoleslp.github.io
  repo-url: https://github.com/sonsoleslp/sonsoleslp.github.io
  google-analytics: "G-251HR7GW52"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@sonsoleslp"
    site: "@sonsoleslp"
    card-style: "summary_large_image"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: publications.qmd
      - href: softwares.qmd
      # - href: blog.qmd
format:
  html:
    theme: 
      - litera
      - custom.scss
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
resources:
  - CNAME
