---
title: "Software"
---

I am skilled in several programming languages such as R, Python, Scala, Java, Ruby, and Javascript (including node.js and React.js). I have developed several open-source libraries and projects related to my research or teaching, as well as industry collaborations.

```{r, include=F}
library(dplyr)
Software = rio::import("cv.xlsx", sheet = "Software")
generateSW <- function(Title,	Description,	Repo,	Demo,	Web) {
  result <- paste0(
  '<h2 id="',gsub(" ", "_", Title),'" class="anchored">',Title,
'<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="#',Title,'" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>',Description,'</p>',

ifelse(is.na(Repo),'',paste0('<a class="btn btn-dark btn-sm" ,="" href="',Repo,'" target="_blank" rel="noopener noreferrer" style="margin-right:5px;">
  <i class="bi bi-github" role="img" aria-label="Github"></i>
  Github
</a>')),
ifelse(is.na(Web),'',paste0('<a class="btn btn-danger btn-sm" ,="" href="',Web,'" target="_blank" rel="noopener noreferrer" style="margin-right:5px;">
  <i class="bi bi-info" role="img" aria-label="Website"></i>
  Website
</a>')),
ifelse(is.na(Demo),'',paste0('<a class="btn btn-warning btn-sm" ,="" href="',Demo,'" target="_blank" rel="noopener noreferrer" style="margin-right:5px;">
  <i class="bi bi-play" role="img" aria-label="Demo"></i>
  Demo
</a>')))
  htmltools::HTML(result)

}

sww<-Software %>% rowwise %>% dplyr::mutate(Text = generateSW(Title,	Description,	Repo,	Demo,	Web) )
```
 
```{r, echo=F, warning=FALSE}



htmltools::HTML(paste(sww$Text,collapse=""))
#htmltools::tagList(list(sww$Text))
```

